/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FeaturesRouteImport } from './routes/_features'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyUsercardRouteImport } from './routes/_study/usercard'
import { Route as FeaturesPhase5Lecture50RouteImport } from './routes/_features/phase5/lecture50'
import { Route as FeaturesPhase5Lecture49RouteImport } from './routes/_features/phase5/lecture49'
import { Route as FeaturesPhase5Lecture48RouteImport } from './routes/_features/phase5/lecture48'
import { Route as FeaturesPhase5Lecture47RouteImport } from './routes/_features/phase5/lecture47'
import { Route as FeaturesPhase5Lecture46RouteImport } from './routes/_features/phase5/lecture46'
import { Route as FeaturesPhase5Lecture45RouteImport } from './routes/_features/phase5/lecture45'
import { Route as FeaturesPhase5Lecture44RouteImport } from './routes/_features/phase5/lecture44'
import { Route as FeaturesPhase5Lecture43RouteImport } from './routes/_features/phase5/lecture43'
import { Route as FeaturesPhase5Lecture42RouteImport } from './routes/_features/phase5/lecture42'
import { Route as FeaturesPhase5Lecture41RouteImport } from './routes/_features/phase5/lecture41'
import { Route as FeaturesPhase4Lecture40RouteImport } from './routes/_features/phase4/lecture40'
import { Route as FeaturesPhase4Lecture39RouteImport } from './routes/_features/phase4/lecture39'
import { Route as FeaturesPhase4Lecture38RouteImport } from './routes/_features/phase4/lecture38'
import { Route as FeaturesPhase4Lecture37RouteImport } from './routes/_features/phase4/lecture37'
import { Route as FeaturesPhase4Lecture36RouteImport } from './routes/_features/phase4/lecture36'
import { Route as FeaturesPhase4Lecture35RouteImport } from './routes/_features/phase4/lecture35'
import { Route as FeaturesPhase4Lecture34RouteImport } from './routes/_features/phase4/lecture34'
import { Route as FeaturesPhase4Lecture33RouteImport } from './routes/_features/phase4/lecture33'
import { Route as FeaturesPhase4Lecture32RouteImport } from './routes/_features/phase4/lecture32'
import { Route as FeaturesPhase4Lecture31RouteImport } from './routes/_features/phase4/lecture31'
import { Route as FeaturesPhase3Lecture30RouteImport } from './routes/_features/phase3/lecture30'
import { Route as FeaturesPhase3Lecture29RouteImport } from './routes/_features/phase3/lecture29'
import { Route as FeaturesPhase3Lecture28RouteImport } from './routes/_features/phase3/lecture28'
import { Route as FeaturesPhase3Lecture27RouteImport } from './routes/_features/phase3/lecture27'
import { Route as FeaturesPhase3Lecture26RouteImport } from './routes/_features/phase3/lecture26'
import { Route as FeaturesPhase3Lecture25RouteImport } from './routes/_features/phase3/lecture25'
import { Route as FeaturesPhase3Lecture24RouteImport } from './routes/_features/phase3/lecture24'
import { Route as FeaturesPhase3Lecture23RouteImport } from './routes/_features/phase3/lecture23'
import { Route as FeaturesPhase3Lecture22RouteImport } from './routes/_features/phase3/lecture22'
import { Route as FeaturesPhase3Lecture21RouteImport } from './routes/_features/phase3/lecture21'
import { Route as FeaturesPhase2Lecture20RouteImport } from './routes/_features/phase2/lecture20'
import { Route as FeaturesPhase2Lecture19RouteImport } from './routes/_features/phase2/lecture19'
import { Route as FeaturesPhase2Lecture18RouteImport } from './routes/_features/phase2/lecture18'
import { Route as FeaturesPhase2Lecture17RouteImport } from './routes/_features/phase2/lecture17'
import { Route as FeaturesPhase2Lecture16RouteImport } from './routes/_features/phase2/lecture16'
import { Route as FeaturesPhase2Lecture15RouteImport } from './routes/_features/phase2/lecture15'
import { Route as FeaturesPhase2Lecture14RouteImport } from './routes/_features/phase2/lecture14'
import { Route as FeaturesPhase2Lecture13RouteImport } from './routes/_features/phase2/lecture13'
import { Route as FeaturesPhase2Lecture12RouteImport } from './routes/_features/phase2/lecture12'
import { Route as FeaturesPhase2Lecture11RouteImport } from './routes/_features/phase2/lecture11'
import { Route as FeaturesPhase1Lecture9RouteImport } from './routes/_features/phase1/lecture9'
import { Route as FeaturesPhase1Lecture8RouteImport } from './routes/_features/phase1/lecture8'
import { Route as FeaturesPhase1Lecture7RouteImport } from './routes/_features/phase1/lecture7'
import { Route as FeaturesPhase1Lecture6RouteImport } from './routes/_features/phase1/lecture6'
import { Route as FeaturesPhase1Lecture5RouteImport } from './routes/_features/phase1/lecture5'
import { Route as FeaturesPhase1Lecture4RouteImport } from './routes/_features/phase1/lecture4'
import { Route as FeaturesPhase1Lecture3RouteImport } from './routes/_features/phase1/lecture3'
import { Route as FeaturesPhase1Lecture2RouteImport } from './routes/_features/phase1/lecture2'
import { Route as FeaturesPhase1Lecture10RouteImport } from './routes/_features/phase1/lecture10'
import { Route as FeaturesPhase1Lecture1RouteImport } from './routes/_features/phase1/lecture1'

const FeaturesRoute = FeaturesRouteImport.update({
  id: '/_features',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyUsercardRoute = StudyUsercardRouteImport.update({
  id: '/_study/usercard',
  path: '/usercard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesPhase5Lecture50Route = FeaturesPhase5Lecture50RouteImport.update({
  id: '/phase5/lecture50',
  path: '/phase5/lecture50',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase5Lecture49Route = FeaturesPhase5Lecture49RouteImport.update({
  id: '/phase5/lecture49',
  path: '/phase5/lecture49',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase5Lecture48Route = FeaturesPhase5Lecture48RouteImport.update({
  id: '/phase5/lecture48',
  path: '/phase5/lecture48',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase5Lecture47Route = FeaturesPhase5Lecture47RouteImport.update({
  id: '/phase5/lecture47',
  path: '/phase5/lecture47',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase5Lecture46Route = FeaturesPhase5Lecture46RouteImport.update({
  id: '/phase5/lecture46',
  path: '/phase5/lecture46',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase5Lecture45Route = FeaturesPhase5Lecture45RouteImport.update({
  id: '/phase5/lecture45',
  path: '/phase5/lecture45',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase5Lecture44Route = FeaturesPhase5Lecture44RouteImport.update({
  id: '/phase5/lecture44',
  path: '/phase5/lecture44',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase5Lecture43Route = FeaturesPhase5Lecture43RouteImport.update({
  id: '/phase5/lecture43',
  path: '/phase5/lecture43',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase5Lecture42Route = FeaturesPhase5Lecture42RouteImport.update({
  id: '/phase5/lecture42',
  path: '/phase5/lecture42',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase5Lecture41Route = FeaturesPhase5Lecture41RouteImport.update({
  id: '/phase5/lecture41',
  path: '/phase5/lecture41',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase4Lecture40Route = FeaturesPhase4Lecture40RouteImport.update({
  id: '/phase4/lecture40',
  path: '/phase4/lecture40',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase4Lecture39Route = FeaturesPhase4Lecture39RouteImport.update({
  id: '/phase4/lecture39',
  path: '/phase4/lecture39',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase4Lecture38Route = FeaturesPhase4Lecture38RouteImport.update({
  id: '/phase4/lecture38',
  path: '/phase4/lecture38',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase4Lecture37Route = FeaturesPhase4Lecture37RouteImport.update({
  id: '/phase4/lecture37',
  path: '/phase4/lecture37',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase4Lecture36Route = FeaturesPhase4Lecture36RouteImport.update({
  id: '/phase4/lecture36',
  path: '/phase4/lecture36',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase4Lecture35Route = FeaturesPhase4Lecture35RouteImport.update({
  id: '/phase4/lecture35',
  path: '/phase4/lecture35',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase4Lecture34Route = FeaturesPhase4Lecture34RouteImport.update({
  id: '/phase4/lecture34',
  path: '/phase4/lecture34',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase4Lecture33Route = FeaturesPhase4Lecture33RouteImport.update({
  id: '/phase4/lecture33',
  path: '/phase4/lecture33',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase4Lecture32Route = FeaturesPhase4Lecture32RouteImport.update({
  id: '/phase4/lecture32',
  path: '/phase4/lecture32',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase4Lecture31Route = FeaturesPhase4Lecture31RouteImport.update({
  id: '/phase4/lecture31',
  path: '/phase4/lecture31',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase3Lecture30Route = FeaturesPhase3Lecture30RouteImport.update({
  id: '/phase3/lecture30',
  path: '/phase3/lecture30',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase3Lecture29Route = FeaturesPhase3Lecture29RouteImport.update({
  id: '/phase3/lecture29',
  path: '/phase3/lecture29',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase3Lecture28Route = FeaturesPhase3Lecture28RouteImport.update({
  id: '/phase3/lecture28',
  path: '/phase3/lecture28',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase3Lecture27Route = FeaturesPhase3Lecture27RouteImport.update({
  id: '/phase3/lecture27',
  path: '/phase3/lecture27',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase3Lecture26Route = FeaturesPhase3Lecture26RouteImport.update({
  id: '/phase3/lecture26',
  path: '/phase3/lecture26',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase3Lecture25Route = FeaturesPhase3Lecture25RouteImport.update({
  id: '/phase3/lecture25',
  path: '/phase3/lecture25',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase3Lecture24Route = FeaturesPhase3Lecture24RouteImport.update({
  id: '/phase3/lecture24',
  path: '/phase3/lecture24',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase3Lecture23Route = FeaturesPhase3Lecture23RouteImport.update({
  id: '/phase3/lecture23',
  path: '/phase3/lecture23',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase3Lecture22Route = FeaturesPhase3Lecture22RouteImport.update({
  id: '/phase3/lecture22',
  path: '/phase3/lecture22',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase3Lecture21Route = FeaturesPhase3Lecture21RouteImport.update({
  id: '/phase3/lecture21',
  path: '/phase3/lecture21',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase2Lecture20Route = FeaturesPhase2Lecture20RouteImport.update({
  id: '/phase2/lecture20',
  path: '/phase2/lecture20',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase2Lecture19Route = FeaturesPhase2Lecture19RouteImport.update({
  id: '/phase2/lecture19',
  path: '/phase2/lecture19',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase2Lecture18Route = FeaturesPhase2Lecture18RouteImport.update({
  id: '/phase2/lecture18',
  path: '/phase2/lecture18',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase2Lecture17Route = FeaturesPhase2Lecture17RouteImport.update({
  id: '/phase2/lecture17',
  path: '/phase2/lecture17',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase2Lecture16Route = FeaturesPhase2Lecture16RouteImport.update({
  id: '/phase2/lecture16',
  path: '/phase2/lecture16',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase2Lecture15Route = FeaturesPhase2Lecture15RouteImport.update({
  id: '/phase2/lecture15',
  path: '/phase2/lecture15',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase2Lecture14Route = FeaturesPhase2Lecture14RouteImport.update({
  id: '/phase2/lecture14',
  path: '/phase2/lecture14',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase2Lecture13Route = FeaturesPhase2Lecture13RouteImport.update({
  id: '/phase2/lecture13',
  path: '/phase2/lecture13',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase2Lecture12Route = FeaturesPhase2Lecture12RouteImport.update({
  id: '/phase2/lecture12',
  path: '/phase2/lecture12',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase2Lecture11Route = FeaturesPhase2Lecture11RouteImport.update({
  id: '/phase2/lecture11',
  path: '/phase2/lecture11',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase1Lecture9Route = FeaturesPhase1Lecture9RouteImport.update({
  id: '/phase1/lecture9',
  path: '/phase1/lecture9',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase1Lecture8Route = FeaturesPhase1Lecture8RouteImport.update({
  id: '/phase1/lecture8',
  path: '/phase1/lecture8',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase1Lecture7Route = FeaturesPhase1Lecture7RouteImport.update({
  id: '/phase1/lecture7',
  path: '/phase1/lecture7',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase1Lecture6Route = FeaturesPhase1Lecture6RouteImport.update({
  id: '/phase1/lecture6',
  path: '/phase1/lecture6',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase1Lecture5Route = FeaturesPhase1Lecture5RouteImport.update({
  id: '/phase1/lecture5',
  path: '/phase1/lecture5',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase1Lecture4Route = FeaturesPhase1Lecture4RouteImport.update({
  id: '/phase1/lecture4',
  path: '/phase1/lecture4',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase1Lecture3Route = FeaturesPhase1Lecture3RouteImport.update({
  id: '/phase1/lecture3',
  path: '/phase1/lecture3',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase1Lecture2Route = FeaturesPhase1Lecture2RouteImport.update({
  id: '/phase1/lecture2',
  path: '/phase1/lecture2',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase1Lecture10Route = FeaturesPhase1Lecture10RouteImport.update({
  id: '/phase1/lecture10',
  path: '/phase1/lecture10',
  getParentRoute: () => FeaturesRoute,
} as any)
const FeaturesPhase1Lecture1Route = FeaturesPhase1Lecture1RouteImport.update({
  id: '/phase1/lecture1',
  path: '/phase1/lecture1',
  getParentRoute: () => FeaturesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/usercard': typeof StudyUsercardRoute
  '/phase1/lecture1': typeof FeaturesPhase1Lecture1Route
  '/phase1/lecture10': typeof FeaturesPhase1Lecture10Route
  '/phase1/lecture2': typeof FeaturesPhase1Lecture2Route
  '/phase1/lecture3': typeof FeaturesPhase1Lecture3Route
  '/phase1/lecture4': typeof FeaturesPhase1Lecture4Route
  '/phase1/lecture5': typeof FeaturesPhase1Lecture5Route
  '/phase1/lecture6': typeof FeaturesPhase1Lecture6Route
  '/phase1/lecture7': typeof FeaturesPhase1Lecture7Route
  '/phase1/lecture8': typeof FeaturesPhase1Lecture8Route
  '/phase1/lecture9': typeof FeaturesPhase1Lecture9Route
  '/phase2/lecture11': typeof FeaturesPhase2Lecture11Route
  '/phase2/lecture12': typeof FeaturesPhase2Lecture12Route
  '/phase2/lecture13': typeof FeaturesPhase2Lecture13Route
  '/phase2/lecture14': typeof FeaturesPhase2Lecture14Route
  '/phase2/lecture15': typeof FeaturesPhase2Lecture15Route
  '/phase2/lecture16': typeof FeaturesPhase2Lecture16Route
  '/phase2/lecture17': typeof FeaturesPhase2Lecture17Route
  '/phase2/lecture18': typeof FeaturesPhase2Lecture18Route
  '/phase2/lecture19': typeof FeaturesPhase2Lecture19Route
  '/phase2/lecture20': typeof FeaturesPhase2Lecture20Route
  '/phase3/lecture21': typeof FeaturesPhase3Lecture21Route
  '/phase3/lecture22': typeof FeaturesPhase3Lecture22Route
  '/phase3/lecture23': typeof FeaturesPhase3Lecture23Route
  '/phase3/lecture24': typeof FeaturesPhase3Lecture24Route
  '/phase3/lecture25': typeof FeaturesPhase3Lecture25Route
  '/phase3/lecture26': typeof FeaturesPhase3Lecture26Route
  '/phase3/lecture27': typeof FeaturesPhase3Lecture27Route
  '/phase3/lecture28': typeof FeaturesPhase3Lecture28Route
  '/phase3/lecture29': typeof FeaturesPhase3Lecture29Route
  '/phase3/lecture30': typeof FeaturesPhase3Lecture30Route
  '/phase4/lecture31': typeof FeaturesPhase4Lecture31Route
  '/phase4/lecture32': typeof FeaturesPhase4Lecture32Route
  '/phase4/lecture33': typeof FeaturesPhase4Lecture33Route
  '/phase4/lecture34': typeof FeaturesPhase4Lecture34Route
  '/phase4/lecture35': typeof FeaturesPhase4Lecture35Route
  '/phase4/lecture36': typeof FeaturesPhase4Lecture36Route
  '/phase4/lecture37': typeof FeaturesPhase4Lecture37Route
  '/phase4/lecture38': typeof FeaturesPhase4Lecture38Route
  '/phase4/lecture39': typeof FeaturesPhase4Lecture39Route
  '/phase4/lecture40': typeof FeaturesPhase4Lecture40Route
  '/phase5/lecture41': typeof FeaturesPhase5Lecture41Route
  '/phase5/lecture42': typeof FeaturesPhase5Lecture42Route
  '/phase5/lecture43': typeof FeaturesPhase5Lecture43Route
  '/phase5/lecture44': typeof FeaturesPhase5Lecture44Route
  '/phase5/lecture45': typeof FeaturesPhase5Lecture45Route
  '/phase5/lecture46': typeof FeaturesPhase5Lecture46Route
  '/phase5/lecture47': typeof FeaturesPhase5Lecture47Route
  '/phase5/lecture48': typeof FeaturesPhase5Lecture48Route
  '/phase5/lecture49': typeof FeaturesPhase5Lecture49Route
  '/phase5/lecture50': typeof FeaturesPhase5Lecture50Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/usercard': typeof StudyUsercardRoute
  '/phase1/lecture1': typeof FeaturesPhase1Lecture1Route
  '/phase1/lecture10': typeof FeaturesPhase1Lecture10Route
  '/phase1/lecture2': typeof FeaturesPhase1Lecture2Route
  '/phase1/lecture3': typeof FeaturesPhase1Lecture3Route
  '/phase1/lecture4': typeof FeaturesPhase1Lecture4Route
  '/phase1/lecture5': typeof FeaturesPhase1Lecture5Route
  '/phase1/lecture6': typeof FeaturesPhase1Lecture6Route
  '/phase1/lecture7': typeof FeaturesPhase1Lecture7Route
  '/phase1/lecture8': typeof FeaturesPhase1Lecture8Route
  '/phase1/lecture9': typeof FeaturesPhase1Lecture9Route
  '/phase2/lecture11': typeof FeaturesPhase2Lecture11Route
  '/phase2/lecture12': typeof FeaturesPhase2Lecture12Route
  '/phase2/lecture13': typeof FeaturesPhase2Lecture13Route
  '/phase2/lecture14': typeof FeaturesPhase2Lecture14Route
  '/phase2/lecture15': typeof FeaturesPhase2Lecture15Route
  '/phase2/lecture16': typeof FeaturesPhase2Lecture16Route
  '/phase2/lecture17': typeof FeaturesPhase2Lecture17Route
  '/phase2/lecture18': typeof FeaturesPhase2Lecture18Route
  '/phase2/lecture19': typeof FeaturesPhase2Lecture19Route
  '/phase2/lecture20': typeof FeaturesPhase2Lecture20Route
  '/phase3/lecture21': typeof FeaturesPhase3Lecture21Route
  '/phase3/lecture22': typeof FeaturesPhase3Lecture22Route
  '/phase3/lecture23': typeof FeaturesPhase3Lecture23Route
  '/phase3/lecture24': typeof FeaturesPhase3Lecture24Route
  '/phase3/lecture25': typeof FeaturesPhase3Lecture25Route
  '/phase3/lecture26': typeof FeaturesPhase3Lecture26Route
  '/phase3/lecture27': typeof FeaturesPhase3Lecture27Route
  '/phase3/lecture28': typeof FeaturesPhase3Lecture28Route
  '/phase3/lecture29': typeof FeaturesPhase3Lecture29Route
  '/phase3/lecture30': typeof FeaturesPhase3Lecture30Route
  '/phase4/lecture31': typeof FeaturesPhase4Lecture31Route
  '/phase4/lecture32': typeof FeaturesPhase4Lecture32Route
  '/phase4/lecture33': typeof FeaturesPhase4Lecture33Route
  '/phase4/lecture34': typeof FeaturesPhase4Lecture34Route
  '/phase4/lecture35': typeof FeaturesPhase4Lecture35Route
  '/phase4/lecture36': typeof FeaturesPhase4Lecture36Route
  '/phase4/lecture37': typeof FeaturesPhase4Lecture37Route
  '/phase4/lecture38': typeof FeaturesPhase4Lecture38Route
  '/phase4/lecture39': typeof FeaturesPhase4Lecture39Route
  '/phase4/lecture40': typeof FeaturesPhase4Lecture40Route
  '/phase5/lecture41': typeof FeaturesPhase5Lecture41Route
  '/phase5/lecture42': typeof FeaturesPhase5Lecture42Route
  '/phase5/lecture43': typeof FeaturesPhase5Lecture43Route
  '/phase5/lecture44': typeof FeaturesPhase5Lecture44Route
  '/phase5/lecture45': typeof FeaturesPhase5Lecture45Route
  '/phase5/lecture46': typeof FeaturesPhase5Lecture46Route
  '/phase5/lecture47': typeof FeaturesPhase5Lecture47Route
  '/phase5/lecture48': typeof FeaturesPhase5Lecture48Route
  '/phase5/lecture49': typeof FeaturesPhase5Lecture49Route
  '/phase5/lecture50': typeof FeaturesPhase5Lecture50Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_features': typeof FeaturesRouteWithChildren
  '/_study/usercard': typeof StudyUsercardRoute
  '/_features/phase1/lecture1': typeof FeaturesPhase1Lecture1Route
  '/_features/phase1/lecture10': typeof FeaturesPhase1Lecture10Route
  '/_features/phase1/lecture2': typeof FeaturesPhase1Lecture2Route
  '/_features/phase1/lecture3': typeof FeaturesPhase1Lecture3Route
  '/_features/phase1/lecture4': typeof FeaturesPhase1Lecture4Route
  '/_features/phase1/lecture5': typeof FeaturesPhase1Lecture5Route
  '/_features/phase1/lecture6': typeof FeaturesPhase1Lecture6Route
  '/_features/phase1/lecture7': typeof FeaturesPhase1Lecture7Route
  '/_features/phase1/lecture8': typeof FeaturesPhase1Lecture8Route
  '/_features/phase1/lecture9': typeof FeaturesPhase1Lecture9Route
  '/_features/phase2/lecture11': typeof FeaturesPhase2Lecture11Route
  '/_features/phase2/lecture12': typeof FeaturesPhase2Lecture12Route
  '/_features/phase2/lecture13': typeof FeaturesPhase2Lecture13Route
  '/_features/phase2/lecture14': typeof FeaturesPhase2Lecture14Route
  '/_features/phase2/lecture15': typeof FeaturesPhase2Lecture15Route
  '/_features/phase2/lecture16': typeof FeaturesPhase2Lecture16Route
  '/_features/phase2/lecture17': typeof FeaturesPhase2Lecture17Route
  '/_features/phase2/lecture18': typeof FeaturesPhase2Lecture18Route
  '/_features/phase2/lecture19': typeof FeaturesPhase2Lecture19Route
  '/_features/phase2/lecture20': typeof FeaturesPhase2Lecture20Route
  '/_features/phase3/lecture21': typeof FeaturesPhase3Lecture21Route
  '/_features/phase3/lecture22': typeof FeaturesPhase3Lecture22Route
  '/_features/phase3/lecture23': typeof FeaturesPhase3Lecture23Route
  '/_features/phase3/lecture24': typeof FeaturesPhase3Lecture24Route
  '/_features/phase3/lecture25': typeof FeaturesPhase3Lecture25Route
  '/_features/phase3/lecture26': typeof FeaturesPhase3Lecture26Route
  '/_features/phase3/lecture27': typeof FeaturesPhase3Lecture27Route
  '/_features/phase3/lecture28': typeof FeaturesPhase3Lecture28Route
  '/_features/phase3/lecture29': typeof FeaturesPhase3Lecture29Route
  '/_features/phase3/lecture30': typeof FeaturesPhase3Lecture30Route
  '/_features/phase4/lecture31': typeof FeaturesPhase4Lecture31Route
  '/_features/phase4/lecture32': typeof FeaturesPhase4Lecture32Route
  '/_features/phase4/lecture33': typeof FeaturesPhase4Lecture33Route
  '/_features/phase4/lecture34': typeof FeaturesPhase4Lecture34Route
  '/_features/phase4/lecture35': typeof FeaturesPhase4Lecture35Route
  '/_features/phase4/lecture36': typeof FeaturesPhase4Lecture36Route
  '/_features/phase4/lecture37': typeof FeaturesPhase4Lecture37Route
  '/_features/phase4/lecture38': typeof FeaturesPhase4Lecture38Route
  '/_features/phase4/lecture39': typeof FeaturesPhase4Lecture39Route
  '/_features/phase4/lecture40': typeof FeaturesPhase4Lecture40Route
  '/_features/phase5/lecture41': typeof FeaturesPhase5Lecture41Route
  '/_features/phase5/lecture42': typeof FeaturesPhase5Lecture42Route
  '/_features/phase5/lecture43': typeof FeaturesPhase5Lecture43Route
  '/_features/phase5/lecture44': typeof FeaturesPhase5Lecture44Route
  '/_features/phase5/lecture45': typeof FeaturesPhase5Lecture45Route
  '/_features/phase5/lecture46': typeof FeaturesPhase5Lecture46Route
  '/_features/phase5/lecture47': typeof FeaturesPhase5Lecture47Route
  '/_features/phase5/lecture48': typeof FeaturesPhase5Lecture48Route
  '/_features/phase5/lecture49': typeof FeaturesPhase5Lecture49Route
  '/_features/phase5/lecture50': typeof FeaturesPhase5Lecture50Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/usercard'
    | '/phase1/lecture1'
    | '/phase1/lecture10'
    | '/phase1/lecture2'
    | '/phase1/lecture3'
    | '/phase1/lecture4'
    | '/phase1/lecture5'
    | '/phase1/lecture6'
    | '/phase1/lecture7'
    | '/phase1/lecture8'
    | '/phase1/lecture9'
    | '/phase2/lecture11'
    | '/phase2/lecture12'
    | '/phase2/lecture13'
    | '/phase2/lecture14'
    | '/phase2/lecture15'
    | '/phase2/lecture16'
    | '/phase2/lecture17'
    | '/phase2/lecture18'
    | '/phase2/lecture19'
    | '/phase2/lecture20'
    | '/phase3/lecture21'
    | '/phase3/lecture22'
    | '/phase3/lecture23'
    | '/phase3/lecture24'
    | '/phase3/lecture25'
    | '/phase3/lecture26'
    | '/phase3/lecture27'
    | '/phase3/lecture28'
    | '/phase3/lecture29'
    | '/phase3/lecture30'
    | '/phase4/lecture31'
    | '/phase4/lecture32'
    | '/phase4/lecture33'
    | '/phase4/lecture34'
    | '/phase4/lecture35'
    | '/phase4/lecture36'
    | '/phase4/lecture37'
    | '/phase4/lecture38'
    | '/phase4/lecture39'
    | '/phase4/lecture40'
    | '/phase5/lecture41'
    | '/phase5/lecture42'
    | '/phase5/lecture43'
    | '/phase5/lecture44'
    | '/phase5/lecture45'
    | '/phase5/lecture46'
    | '/phase5/lecture47'
    | '/phase5/lecture48'
    | '/phase5/lecture49'
    | '/phase5/lecture50'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/usercard'
    | '/phase1/lecture1'
    | '/phase1/lecture10'
    | '/phase1/lecture2'
    | '/phase1/lecture3'
    | '/phase1/lecture4'
    | '/phase1/lecture5'
    | '/phase1/lecture6'
    | '/phase1/lecture7'
    | '/phase1/lecture8'
    | '/phase1/lecture9'
    | '/phase2/lecture11'
    | '/phase2/lecture12'
    | '/phase2/lecture13'
    | '/phase2/lecture14'
    | '/phase2/lecture15'
    | '/phase2/lecture16'
    | '/phase2/lecture17'
    | '/phase2/lecture18'
    | '/phase2/lecture19'
    | '/phase2/lecture20'
    | '/phase3/lecture21'
    | '/phase3/lecture22'
    | '/phase3/lecture23'
    | '/phase3/lecture24'
    | '/phase3/lecture25'
    | '/phase3/lecture26'
    | '/phase3/lecture27'
    | '/phase3/lecture28'
    | '/phase3/lecture29'
    | '/phase3/lecture30'
    | '/phase4/lecture31'
    | '/phase4/lecture32'
    | '/phase4/lecture33'
    | '/phase4/lecture34'
    | '/phase4/lecture35'
    | '/phase4/lecture36'
    | '/phase4/lecture37'
    | '/phase4/lecture38'
    | '/phase4/lecture39'
    | '/phase4/lecture40'
    | '/phase5/lecture41'
    | '/phase5/lecture42'
    | '/phase5/lecture43'
    | '/phase5/lecture44'
    | '/phase5/lecture45'
    | '/phase5/lecture46'
    | '/phase5/lecture47'
    | '/phase5/lecture48'
    | '/phase5/lecture49'
    | '/phase5/lecture50'
  id:
    | '__root__'
    | '/'
    | '/_features'
    | '/_study/usercard'
    | '/_features/phase1/lecture1'
    | '/_features/phase1/lecture10'
    | '/_features/phase1/lecture2'
    | '/_features/phase1/lecture3'
    | '/_features/phase1/lecture4'
    | '/_features/phase1/lecture5'
    | '/_features/phase1/lecture6'
    | '/_features/phase1/lecture7'
    | '/_features/phase1/lecture8'
    | '/_features/phase1/lecture9'
    | '/_features/phase2/lecture11'
    | '/_features/phase2/lecture12'
    | '/_features/phase2/lecture13'
    | '/_features/phase2/lecture14'
    | '/_features/phase2/lecture15'
    | '/_features/phase2/lecture16'
    | '/_features/phase2/lecture17'
    | '/_features/phase2/lecture18'
    | '/_features/phase2/lecture19'
    | '/_features/phase2/lecture20'
    | '/_features/phase3/lecture21'
    | '/_features/phase3/lecture22'
    | '/_features/phase3/lecture23'
    | '/_features/phase3/lecture24'
    | '/_features/phase3/lecture25'
    | '/_features/phase3/lecture26'
    | '/_features/phase3/lecture27'
    | '/_features/phase3/lecture28'
    | '/_features/phase3/lecture29'
    | '/_features/phase3/lecture30'
    | '/_features/phase4/lecture31'
    | '/_features/phase4/lecture32'
    | '/_features/phase4/lecture33'
    | '/_features/phase4/lecture34'
    | '/_features/phase4/lecture35'
    | '/_features/phase4/lecture36'
    | '/_features/phase4/lecture37'
    | '/_features/phase4/lecture38'
    | '/_features/phase4/lecture39'
    | '/_features/phase4/lecture40'
    | '/_features/phase5/lecture41'
    | '/_features/phase5/lecture42'
    | '/_features/phase5/lecture43'
    | '/_features/phase5/lecture44'
    | '/_features/phase5/lecture45'
    | '/_features/phase5/lecture46'
    | '/_features/phase5/lecture47'
    | '/_features/phase5/lecture48'
    | '/_features/phase5/lecture49'
    | '/_features/phase5/lecture50'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeaturesRoute: typeof FeaturesRouteWithChildren
  StudyUsercardRoute: typeof StudyUsercardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_features': {
      id: '/_features'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_study/usercard': {
      id: '/_study/usercard'
      path: '/usercard'
      fullPath: '/usercard'
      preLoaderRoute: typeof StudyUsercardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_features/phase5/lecture50': {
      id: '/_features/phase5/lecture50'
      path: '/phase5/lecture50'
      fullPath: '/phase5/lecture50'
      preLoaderRoute: typeof FeaturesPhase5Lecture50RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase5/lecture49': {
      id: '/_features/phase5/lecture49'
      path: '/phase5/lecture49'
      fullPath: '/phase5/lecture49'
      preLoaderRoute: typeof FeaturesPhase5Lecture49RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase5/lecture48': {
      id: '/_features/phase5/lecture48'
      path: '/phase5/lecture48'
      fullPath: '/phase5/lecture48'
      preLoaderRoute: typeof FeaturesPhase5Lecture48RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase5/lecture47': {
      id: '/_features/phase5/lecture47'
      path: '/phase5/lecture47'
      fullPath: '/phase5/lecture47'
      preLoaderRoute: typeof FeaturesPhase5Lecture47RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase5/lecture46': {
      id: '/_features/phase5/lecture46'
      path: '/phase5/lecture46'
      fullPath: '/phase5/lecture46'
      preLoaderRoute: typeof FeaturesPhase5Lecture46RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase5/lecture45': {
      id: '/_features/phase5/lecture45'
      path: '/phase5/lecture45'
      fullPath: '/phase5/lecture45'
      preLoaderRoute: typeof FeaturesPhase5Lecture45RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase5/lecture44': {
      id: '/_features/phase5/lecture44'
      path: '/phase5/lecture44'
      fullPath: '/phase5/lecture44'
      preLoaderRoute: typeof FeaturesPhase5Lecture44RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase5/lecture43': {
      id: '/_features/phase5/lecture43'
      path: '/phase5/lecture43'
      fullPath: '/phase5/lecture43'
      preLoaderRoute: typeof FeaturesPhase5Lecture43RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase5/lecture42': {
      id: '/_features/phase5/lecture42'
      path: '/phase5/lecture42'
      fullPath: '/phase5/lecture42'
      preLoaderRoute: typeof FeaturesPhase5Lecture42RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase5/lecture41': {
      id: '/_features/phase5/lecture41'
      path: '/phase5/lecture41'
      fullPath: '/phase5/lecture41'
      preLoaderRoute: typeof FeaturesPhase5Lecture41RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase4/lecture40': {
      id: '/_features/phase4/lecture40'
      path: '/phase4/lecture40'
      fullPath: '/phase4/lecture40'
      preLoaderRoute: typeof FeaturesPhase4Lecture40RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase4/lecture39': {
      id: '/_features/phase4/lecture39'
      path: '/phase4/lecture39'
      fullPath: '/phase4/lecture39'
      preLoaderRoute: typeof FeaturesPhase4Lecture39RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase4/lecture38': {
      id: '/_features/phase4/lecture38'
      path: '/phase4/lecture38'
      fullPath: '/phase4/lecture38'
      preLoaderRoute: typeof FeaturesPhase4Lecture38RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase4/lecture37': {
      id: '/_features/phase4/lecture37'
      path: '/phase4/lecture37'
      fullPath: '/phase4/lecture37'
      preLoaderRoute: typeof FeaturesPhase4Lecture37RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase4/lecture36': {
      id: '/_features/phase4/lecture36'
      path: '/phase4/lecture36'
      fullPath: '/phase4/lecture36'
      preLoaderRoute: typeof FeaturesPhase4Lecture36RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase4/lecture35': {
      id: '/_features/phase4/lecture35'
      path: '/phase4/lecture35'
      fullPath: '/phase4/lecture35'
      preLoaderRoute: typeof FeaturesPhase4Lecture35RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase4/lecture34': {
      id: '/_features/phase4/lecture34'
      path: '/phase4/lecture34'
      fullPath: '/phase4/lecture34'
      preLoaderRoute: typeof FeaturesPhase4Lecture34RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase4/lecture33': {
      id: '/_features/phase4/lecture33'
      path: '/phase4/lecture33'
      fullPath: '/phase4/lecture33'
      preLoaderRoute: typeof FeaturesPhase4Lecture33RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase4/lecture32': {
      id: '/_features/phase4/lecture32'
      path: '/phase4/lecture32'
      fullPath: '/phase4/lecture32'
      preLoaderRoute: typeof FeaturesPhase4Lecture32RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase4/lecture31': {
      id: '/_features/phase4/lecture31'
      path: '/phase4/lecture31'
      fullPath: '/phase4/lecture31'
      preLoaderRoute: typeof FeaturesPhase4Lecture31RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase3/lecture30': {
      id: '/_features/phase3/lecture30'
      path: '/phase3/lecture30'
      fullPath: '/phase3/lecture30'
      preLoaderRoute: typeof FeaturesPhase3Lecture30RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase3/lecture29': {
      id: '/_features/phase3/lecture29'
      path: '/phase3/lecture29'
      fullPath: '/phase3/lecture29'
      preLoaderRoute: typeof FeaturesPhase3Lecture29RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase3/lecture28': {
      id: '/_features/phase3/lecture28'
      path: '/phase3/lecture28'
      fullPath: '/phase3/lecture28'
      preLoaderRoute: typeof FeaturesPhase3Lecture28RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase3/lecture27': {
      id: '/_features/phase3/lecture27'
      path: '/phase3/lecture27'
      fullPath: '/phase3/lecture27'
      preLoaderRoute: typeof FeaturesPhase3Lecture27RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase3/lecture26': {
      id: '/_features/phase3/lecture26'
      path: '/phase3/lecture26'
      fullPath: '/phase3/lecture26'
      preLoaderRoute: typeof FeaturesPhase3Lecture26RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase3/lecture25': {
      id: '/_features/phase3/lecture25'
      path: '/phase3/lecture25'
      fullPath: '/phase3/lecture25'
      preLoaderRoute: typeof FeaturesPhase3Lecture25RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase3/lecture24': {
      id: '/_features/phase3/lecture24'
      path: '/phase3/lecture24'
      fullPath: '/phase3/lecture24'
      preLoaderRoute: typeof FeaturesPhase3Lecture24RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase3/lecture23': {
      id: '/_features/phase3/lecture23'
      path: '/phase3/lecture23'
      fullPath: '/phase3/lecture23'
      preLoaderRoute: typeof FeaturesPhase3Lecture23RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase3/lecture22': {
      id: '/_features/phase3/lecture22'
      path: '/phase3/lecture22'
      fullPath: '/phase3/lecture22'
      preLoaderRoute: typeof FeaturesPhase3Lecture22RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase3/lecture21': {
      id: '/_features/phase3/lecture21'
      path: '/phase3/lecture21'
      fullPath: '/phase3/lecture21'
      preLoaderRoute: typeof FeaturesPhase3Lecture21RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase2/lecture20': {
      id: '/_features/phase2/lecture20'
      path: '/phase2/lecture20'
      fullPath: '/phase2/lecture20'
      preLoaderRoute: typeof FeaturesPhase2Lecture20RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase2/lecture19': {
      id: '/_features/phase2/lecture19'
      path: '/phase2/lecture19'
      fullPath: '/phase2/lecture19'
      preLoaderRoute: typeof FeaturesPhase2Lecture19RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase2/lecture18': {
      id: '/_features/phase2/lecture18'
      path: '/phase2/lecture18'
      fullPath: '/phase2/lecture18'
      preLoaderRoute: typeof FeaturesPhase2Lecture18RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase2/lecture17': {
      id: '/_features/phase2/lecture17'
      path: '/phase2/lecture17'
      fullPath: '/phase2/lecture17'
      preLoaderRoute: typeof FeaturesPhase2Lecture17RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase2/lecture16': {
      id: '/_features/phase2/lecture16'
      path: '/phase2/lecture16'
      fullPath: '/phase2/lecture16'
      preLoaderRoute: typeof FeaturesPhase2Lecture16RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase2/lecture15': {
      id: '/_features/phase2/lecture15'
      path: '/phase2/lecture15'
      fullPath: '/phase2/lecture15'
      preLoaderRoute: typeof FeaturesPhase2Lecture15RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase2/lecture14': {
      id: '/_features/phase2/lecture14'
      path: '/phase2/lecture14'
      fullPath: '/phase2/lecture14'
      preLoaderRoute: typeof FeaturesPhase2Lecture14RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase2/lecture13': {
      id: '/_features/phase2/lecture13'
      path: '/phase2/lecture13'
      fullPath: '/phase2/lecture13'
      preLoaderRoute: typeof FeaturesPhase2Lecture13RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase2/lecture12': {
      id: '/_features/phase2/lecture12'
      path: '/phase2/lecture12'
      fullPath: '/phase2/lecture12'
      preLoaderRoute: typeof FeaturesPhase2Lecture12RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase2/lecture11': {
      id: '/_features/phase2/lecture11'
      path: '/phase2/lecture11'
      fullPath: '/phase2/lecture11'
      preLoaderRoute: typeof FeaturesPhase2Lecture11RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase1/lecture9': {
      id: '/_features/phase1/lecture9'
      path: '/phase1/lecture9'
      fullPath: '/phase1/lecture9'
      preLoaderRoute: typeof FeaturesPhase1Lecture9RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase1/lecture8': {
      id: '/_features/phase1/lecture8'
      path: '/phase1/lecture8'
      fullPath: '/phase1/lecture8'
      preLoaderRoute: typeof FeaturesPhase1Lecture8RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase1/lecture7': {
      id: '/_features/phase1/lecture7'
      path: '/phase1/lecture7'
      fullPath: '/phase1/lecture7'
      preLoaderRoute: typeof FeaturesPhase1Lecture7RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase1/lecture6': {
      id: '/_features/phase1/lecture6'
      path: '/phase1/lecture6'
      fullPath: '/phase1/lecture6'
      preLoaderRoute: typeof FeaturesPhase1Lecture6RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase1/lecture5': {
      id: '/_features/phase1/lecture5'
      path: '/phase1/lecture5'
      fullPath: '/phase1/lecture5'
      preLoaderRoute: typeof FeaturesPhase1Lecture5RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase1/lecture4': {
      id: '/_features/phase1/lecture4'
      path: '/phase1/lecture4'
      fullPath: '/phase1/lecture4'
      preLoaderRoute: typeof FeaturesPhase1Lecture4RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase1/lecture3': {
      id: '/_features/phase1/lecture3'
      path: '/phase1/lecture3'
      fullPath: '/phase1/lecture3'
      preLoaderRoute: typeof FeaturesPhase1Lecture3RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase1/lecture2': {
      id: '/_features/phase1/lecture2'
      path: '/phase1/lecture2'
      fullPath: '/phase1/lecture2'
      preLoaderRoute: typeof FeaturesPhase1Lecture2RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase1/lecture10': {
      id: '/_features/phase1/lecture10'
      path: '/phase1/lecture10'
      fullPath: '/phase1/lecture10'
      preLoaderRoute: typeof FeaturesPhase1Lecture10RouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_features/phase1/lecture1': {
      id: '/_features/phase1/lecture1'
      path: '/phase1/lecture1'
      fullPath: '/phase1/lecture1'
      preLoaderRoute: typeof FeaturesPhase1Lecture1RouteImport
      parentRoute: typeof FeaturesRoute
    }
  }
}

interface FeaturesRouteChildren {
  FeaturesPhase1Lecture1Route: typeof FeaturesPhase1Lecture1Route
  FeaturesPhase1Lecture10Route: typeof FeaturesPhase1Lecture10Route
  FeaturesPhase1Lecture2Route: typeof FeaturesPhase1Lecture2Route
  FeaturesPhase1Lecture3Route: typeof FeaturesPhase1Lecture3Route
  FeaturesPhase1Lecture4Route: typeof FeaturesPhase1Lecture4Route
  FeaturesPhase1Lecture5Route: typeof FeaturesPhase1Lecture5Route
  FeaturesPhase1Lecture6Route: typeof FeaturesPhase1Lecture6Route
  FeaturesPhase1Lecture7Route: typeof FeaturesPhase1Lecture7Route
  FeaturesPhase1Lecture8Route: typeof FeaturesPhase1Lecture8Route
  FeaturesPhase1Lecture9Route: typeof FeaturesPhase1Lecture9Route
  FeaturesPhase2Lecture11Route: typeof FeaturesPhase2Lecture11Route
  FeaturesPhase2Lecture12Route: typeof FeaturesPhase2Lecture12Route
  FeaturesPhase2Lecture13Route: typeof FeaturesPhase2Lecture13Route
  FeaturesPhase2Lecture14Route: typeof FeaturesPhase2Lecture14Route
  FeaturesPhase2Lecture15Route: typeof FeaturesPhase2Lecture15Route
  FeaturesPhase2Lecture16Route: typeof FeaturesPhase2Lecture16Route
  FeaturesPhase2Lecture17Route: typeof FeaturesPhase2Lecture17Route
  FeaturesPhase2Lecture18Route: typeof FeaturesPhase2Lecture18Route
  FeaturesPhase2Lecture19Route: typeof FeaturesPhase2Lecture19Route
  FeaturesPhase2Lecture20Route: typeof FeaturesPhase2Lecture20Route
  FeaturesPhase3Lecture21Route: typeof FeaturesPhase3Lecture21Route
  FeaturesPhase3Lecture22Route: typeof FeaturesPhase3Lecture22Route
  FeaturesPhase3Lecture23Route: typeof FeaturesPhase3Lecture23Route
  FeaturesPhase3Lecture24Route: typeof FeaturesPhase3Lecture24Route
  FeaturesPhase3Lecture25Route: typeof FeaturesPhase3Lecture25Route
  FeaturesPhase3Lecture26Route: typeof FeaturesPhase3Lecture26Route
  FeaturesPhase3Lecture27Route: typeof FeaturesPhase3Lecture27Route
  FeaturesPhase3Lecture28Route: typeof FeaturesPhase3Lecture28Route
  FeaturesPhase3Lecture29Route: typeof FeaturesPhase3Lecture29Route
  FeaturesPhase3Lecture30Route: typeof FeaturesPhase3Lecture30Route
  FeaturesPhase4Lecture31Route: typeof FeaturesPhase4Lecture31Route
  FeaturesPhase4Lecture32Route: typeof FeaturesPhase4Lecture32Route
  FeaturesPhase4Lecture33Route: typeof FeaturesPhase4Lecture33Route
  FeaturesPhase4Lecture34Route: typeof FeaturesPhase4Lecture34Route
  FeaturesPhase4Lecture35Route: typeof FeaturesPhase4Lecture35Route
  FeaturesPhase4Lecture36Route: typeof FeaturesPhase4Lecture36Route
  FeaturesPhase4Lecture37Route: typeof FeaturesPhase4Lecture37Route
  FeaturesPhase4Lecture38Route: typeof FeaturesPhase4Lecture38Route
  FeaturesPhase4Lecture39Route: typeof FeaturesPhase4Lecture39Route
  FeaturesPhase4Lecture40Route: typeof FeaturesPhase4Lecture40Route
  FeaturesPhase5Lecture41Route: typeof FeaturesPhase5Lecture41Route
  FeaturesPhase5Lecture42Route: typeof FeaturesPhase5Lecture42Route
  FeaturesPhase5Lecture43Route: typeof FeaturesPhase5Lecture43Route
  FeaturesPhase5Lecture44Route: typeof FeaturesPhase5Lecture44Route
  FeaturesPhase5Lecture45Route: typeof FeaturesPhase5Lecture45Route
  FeaturesPhase5Lecture46Route: typeof FeaturesPhase5Lecture46Route
  FeaturesPhase5Lecture47Route: typeof FeaturesPhase5Lecture47Route
  FeaturesPhase5Lecture48Route: typeof FeaturesPhase5Lecture48Route
  FeaturesPhase5Lecture49Route: typeof FeaturesPhase5Lecture49Route
  FeaturesPhase5Lecture50Route: typeof FeaturesPhase5Lecture50Route
}

const FeaturesRouteChildren: FeaturesRouteChildren = {
  FeaturesPhase1Lecture1Route: FeaturesPhase1Lecture1Route,
  FeaturesPhase1Lecture10Route: FeaturesPhase1Lecture10Route,
  FeaturesPhase1Lecture2Route: FeaturesPhase1Lecture2Route,
  FeaturesPhase1Lecture3Route: FeaturesPhase1Lecture3Route,
  FeaturesPhase1Lecture4Route: FeaturesPhase1Lecture4Route,
  FeaturesPhase1Lecture5Route: FeaturesPhase1Lecture5Route,
  FeaturesPhase1Lecture6Route: FeaturesPhase1Lecture6Route,
  FeaturesPhase1Lecture7Route: FeaturesPhase1Lecture7Route,
  FeaturesPhase1Lecture8Route: FeaturesPhase1Lecture8Route,
  FeaturesPhase1Lecture9Route: FeaturesPhase1Lecture9Route,
  FeaturesPhase2Lecture11Route: FeaturesPhase2Lecture11Route,
  FeaturesPhase2Lecture12Route: FeaturesPhase2Lecture12Route,
  FeaturesPhase2Lecture13Route: FeaturesPhase2Lecture13Route,
  FeaturesPhase2Lecture14Route: FeaturesPhase2Lecture14Route,
  FeaturesPhase2Lecture15Route: FeaturesPhase2Lecture15Route,
  FeaturesPhase2Lecture16Route: FeaturesPhase2Lecture16Route,
  FeaturesPhase2Lecture17Route: FeaturesPhase2Lecture17Route,
  FeaturesPhase2Lecture18Route: FeaturesPhase2Lecture18Route,
  FeaturesPhase2Lecture19Route: FeaturesPhase2Lecture19Route,
  FeaturesPhase2Lecture20Route: FeaturesPhase2Lecture20Route,
  FeaturesPhase3Lecture21Route: FeaturesPhase3Lecture21Route,
  FeaturesPhase3Lecture22Route: FeaturesPhase3Lecture22Route,
  FeaturesPhase3Lecture23Route: FeaturesPhase3Lecture23Route,
  FeaturesPhase3Lecture24Route: FeaturesPhase3Lecture24Route,
  FeaturesPhase3Lecture25Route: FeaturesPhase3Lecture25Route,
  FeaturesPhase3Lecture26Route: FeaturesPhase3Lecture26Route,
  FeaturesPhase3Lecture27Route: FeaturesPhase3Lecture27Route,
  FeaturesPhase3Lecture28Route: FeaturesPhase3Lecture28Route,
  FeaturesPhase3Lecture29Route: FeaturesPhase3Lecture29Route,
  FeaturesPhase3Lecture30Route: FeaturesPhase3Lecture30Route,
  FeaturesPhase4Lecture31Route: FeaturesPhase4Lecture31Route,
  FeaturesPhase4Lecture32Route: FeaturesPhase4Lecture32Route,
  FeaturesPhase4Lecture33Route: FeaturesPhase4Lecture33Route,
  FeaturesPhase4Lecture34Route: FeaturesPhase4Lecture34Route,
  FeaturesPhase4Lecture35Route: FeaturesPhase4Lecture35Route,
  FeaturesPhase4Lecture36Route: FeaturesPhase4Lecture36Route,
  FeaturesPhase4Lecture37Route: FeaturesPhase4Lecture37Route,
  FeaturesPhase4Lecture38Route: FeaturesPhase4Lecture38Route,
  FeaturesPhase4Lecture39Route: FeaturesPhase4Lecture39Route,
  FeaturesPhase4Lecture40Route: FeaturesPhase4Lecture40Route,
  FeaturesPhase5Lecture41Route: FeaturesPhase5Lecture41Route,
  FeaturesPhase5Lecture42Route: FeaturesPhase5Lecture42Route,
  FeaturesPhase5Lecture43Route: FeaturesPhase5Lecture43Route,
  FeaturesPhase5Lecture44Route: FeaturesPhase5Lecture44Route,
  FeaturesPhase5Lecture45Route: FeaturesPhase5Lecture45Route,
  FeaturesPhase5Lecture46Route: FeaturesPhase5Lecture46Route,
  FeaturesPhase5Lecture47Route: FeaturesPhase5Lecture47Route,
  FeaturesPhase5Lecture48Route: FeaturesPhase5Lecture48Route,
  FeaturesPhase5Lecture49Route: FeaturesPhase5Lecture49Route,
  FeaturesPhase5Lecture50Route: FeaturesPhase5Lecture50Route,
}

const FeaturesRouteWithChildren = FeaturesRoute._addFileChildren(
  FeaturesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeaturesRoute: FeaturesRouteWithChildren,
  StudyUsercardRoute: StudyUsercardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
